plugins {
	id 'idea'
	id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
	id 'org.spongepowered.mixin' version '0.7.+'
	id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = "$baseVersion+$branch"
archivesBaseName = project.slug


repositories {
	maven {
		name = "Curse maven"
		url = "https://cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	mavenCentral()
	mavenLocal()
}

dependencies {
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
	minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}" //21

	implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.2.0"))
	implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.2.0")) {
		jarJar.ranged(it, "[0.2.0,)")
	}
}

processResources {
    final Map<String, String> meta = [
            version       : version,
            modId         : modId,
            modName       : modName,
            modDescription: modDescription,
            homepage      : "https://modrinth.com/mod/${slug}",
            issues        : "https://github.com/${user}/${slug}/issues",
            sources       : "https://github.com/${user}/${slug}",
            license       : license,
            authors       : authors,
            contributors  : contributors,
            members       : "${authors}. Contributions by ${contributors}",
            mc            : libs.versions.minecraft.get(),
            forge         : libs.versions.forge.get(),
            lib39         : libs.versions.lib39.get(),
    ]
    inputs.properties(meta)
    filesMatching("META-INF/mods.toml") { expand(meta) }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${archivesBaseName}" }
    }
}

minecraft {
    mappings channel: "official", version: "1.20.1"
	accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file("run")
            property "forge.logging.console.level", "debug"
            mods {
                "$modId" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file("run")
            property "forge.logging.console.level", "debug"
            mods {
                "$modId" {
                    source sourceSets.main
                }
            }
        }
    }
}
