modLoader="javafml"
loaderVersion="[47,)"
license="${license}"
issueTrackerURL="${issues}"
showAsResourcePack=false

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''
logoFile="assets/${modId}/icon.png"
displayURL="${homepage}"

[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc}]"
    ordering="NONE"
    side="BOTH"
